name: task_flow
description: "Proyecto TaskFlow - Gestión de Tareas del Equipo 2"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # Iconos estándar para iOS y Android
  cupertino_icons: ^1.0.8
  # Sistema de navegación profesional (Requisito de Echeverria Pacheco)
  go_router: ^17.1.0
  shared_preferences: ^2.5.4
  flutter_riverpod: ^2.5.1 
  # Base de datos local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Serialización JSON
  json_annotation: ^4.9.0
  # Para la navegación avanzada
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Reglas de estilo de código para evitar errores
  flutter_lints: ^5.0.0
  # Herramientas para generar los modelos JSON automáticamente
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0


flutter:
  # REQUISITO: Activación de Material 3 para el diseño de Dzul Ortega
  uses-material-design: true

  # CONFIGURACIÓN DE ASSETS: Registro de recursos visuales
  # Nota: Es fundamental respetar los 2 espacios de sangría en 'assets:'
  #assets:
    #- assets/images/